# site properties and page defaults
title: HSA4ESMLS
subtitle: PPoSS: LARGE: Co-designing Hardware, Software, and Algorithms to Enable Extreme-Scale Machine Learning Systems.\n University of Virginia; University of Maryland, College Park & University of Pittsburgh; Saint Louis University
description: The newly emerging AI of Things (AIoT) and Internet of Senses (IoS) systems will make mobile and embedded devices smart, communicative, and powerful to process data and make intelligent decisions, by integrating the Internet of Things (IoT) and Artificial Intelligence (AI). This project aims to provide a new generation of systems, algorithms, and tools to facilitate such deep integration at extreme scale. The project’s novelty is to fundamentally ensure scalability of future Machine Learning (ML) systems over the large population of distributed devices, by formulating the seamless integration of advanced ML algorithms with co-designed hardware, computer architectures, and distributed edge-cloud systems, along with meaningful security and privacy guarantees. This co-design methodology allows synergistic consideration of the intrinsic heterogeneity, performance and energy constraints of devices, as well as the unprecedented scale and complexity of data produced by these devices. The project’s impacts are to lay the foundation for the future of AIoT and IoS systems by solving challenges driven by needs related to their complex and heterogeneous contexts, and to advance a wide swath of fields including ML, edge computing, IoT, hardware, software and related engineering disciplines. This project is also contributing to society through developing new curricula, disseminating research for education and training, engaging under-represented students in research, and outreaching to high-school students. The primary goal of this project is to build a new co-designed framework of hardware, software, and algorithms to enable extreme-scale ML systems for the emerging AIoT and IoS systems. The project consists of five research thrusts: Thrust 1 develops hardware, computer architecture and compiler approaches to address the scalability issue in AIoT and IoS systems by enforcing large-scale split learning on devices. Thrust 2 investigates extreme-scale ML on weak embedded devices by designing a new system framework that adaptively partitions and offloads the ML computing workloads. Thrust 3 addresses system and data unreliability by designing new cross-layer algorithms and hardware techniques. Thrust 4 investigates algorithm, hardware and software co-design to enable secure and privacy-preserving ML systems at scale. Thrust 5 involves designing and implementing an IoS testbed and a smart building testbed to evaluate the proposed system designs.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: contact@HSA4ESMLS.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: HSA4ESMLS
  twitter: HSA4ESMLS
  youtube: HSA4ESMLS

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
